title : Pulchra Agri
description: 'Pulchra Agri'

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
plugins: [jekyll-gist, jekyll-paginate]
permalink: /:year/:month/:title.html
